server:
  port: 7003

redis:
  connection: ${services.redis.connection:redis://localhost:6379}

okHttpClient:
  retries:
    maxElapsedBackoffMs: 5000

endpoints:
  health:
    sensitive: false

services:
  front50:
    baseUrl: http://localhost:8080
# For options, see com.netflix.spinnaker.fiat.config.FiatServerConfigurationProperties
